apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pc-0-infra-core.yaml
  - pc-1-operators.yaml
  - pc-2-secrets-certs.yaml
  - pc-3-registry-harbor.yaml
  - pc-4-databases.yaml
  - pc-5-management-auth.yaml
  - pc-6-apps-priority.yaml
  - pc-7-apps-idle.yaml
  - pc-8-background-jobs.yaml
