apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pc-1-operators
value: 900000
globalDefault: false
description: "Prioridade para operators (Percona PostgreSQL, MongoDB, EMQX, Keycloak, etc.)."
