apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: pc-2-secrets-certs
value: 800000
globalDefault: false
description: "Prioridade para secrets e certificados (Sealed Secrets, External Secrets, Cert-Manager, etc.)."
