apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cilium

sortOptions:
  order: fifo

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/experimental-install.yaml
  - namespace.yaml
  - gatewayclass.yaml
  - gateway-public.yaml
  - policy.yaml
  - lb-pool.yaml
