---
galaxy_info:
  author: Broetec
  description: Prepare the KVM/libvirt host (bootstrap, NAT network, firewalld).
  license: MIT
  min_ansible_version: "2.14"
  galaxy_tags:
    - kvm
    - libvirt

dependencies: []
